parameters:
#    lowpress_test.example.class: Lowpress\TestBundle\Example

services:
#    lowpress_test.example:
#        class: %lowpress_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
