parameters:
    lowpress_wordpress.wordpress_extension.class: Lowpress\WordpressBundle\Twig\WordpressExtension

services:
    lowpress_wordpress.wordpress_extension:
        class: %lowpress_wordpress.wordpress_extension.class%
        tags:
            -  { name: twig.extension }